[package]
name = "jaf"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
serde_json = "1.0"
tokio-util = { version = "0.7", features = ["io", "compat"] }
futures = "0.3"
bytes = "1.0"
warp = "0.3"
